config/routes.rb
Rails.application.routes.draw do

  resources :mining_types
  #rota get para welcome/index
  get 'welcome/index'

  #outra forma de escrever uma rota com um alias
  get '/inicio', to: 'welcome#index'

 #resources serve para escrever as 7 rotas de uma vez dos metodos HTTP
  resources :coins

  # root to: manda a rota principal quando acessar ex: localhost:3000
  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord

  belongs_to :mining_type

  validates :acronym, presence: true
  validates :description, presence: true
end

app/models/mining_type.rb
class MiningType < ApplicationRecord

  has_many :coins

  validates :acronym, presence: true
  validates :description, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale
        if params[:locale]
            cookies[:locale] = params[:locale]
        end

        if cookies[:locale]
            if I18n.locale != cookies[:locale]
                I18n.locale = cookies[:locale]
            end
        end
    end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController

  before_action :set_coin, only: [:show, :edit, :update, :destroy]
  before_action :set_mining_type, only: [:new, :edit, :update, :create]

  def index
    @coins = Coin.all
  end

  def show
  end

  def new
    @coin = Coin.new
  end

  def edit;  end

  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coins_path, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html do
          flash.now[:error] = @coin.errors.full_messages.to_sentence
          render :new, status: :unprocessable_entity
        end
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coins_path, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html do
          flash.now[:error] = @coin.errors.full_messages.to_sentence
          render :new, status: :unprocessable_entity
        end
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_coin
      @coin = Coin.find(params[:id])
    end

    def coin_params
      params.require(:coin).permit(:description, :acronym, :urlImage, :mining_type_id)
    end

    def set_mining_type
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: [:show, :edit, :update, :destroy]

  def index
    @mining_types = MiningType.all
  end

  def show
  end

  def new
    @mining_type = MiningType.new
  end

  def edit;  end

  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_types_path, notice: 'Mining type was successfully created.' }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html do
          flash.now[:error] = @mining_type.errors.full_messages.to_sentence
          render :new, status: :unprocessable_entity
        end
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_types_path, notice: 'Mining type was successfully updated.' }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html do
          flash.now[:error] = @mining_type.errors.full_messages.to_sentence
          render :edit, status: :unprocessable_entity
        end
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: 'Mining type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #queryParams
  def index
    # cookies[:curso] = "Curso de Ruby On Rails"
    @meu_nome = "César" || params[:nome]
    @meu_curso = "Ruby on Rails" || params[:curso]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_br(data_us)
    data_us.strftime("%d/%m/%Y")
  end

  def locale
    I18n.locale == :en ? "Estados Unidos" : "Português do Brasil"
  end

  def ambiente_rails
    if Rails.env.development?
      "Desenvolvimento"
      elsif Rails.env.production?
        "Produção"
      else
          "Teste"
    end
  end

  def translate(language)
    request.path + "?locale=#{language}"
  end

  def display_flash_messages
    notify = flash.map do |type, message|
      type = get_type_notify(type)
      "$.notify(\"#{message}\", '#{type}')"
    end.join
    flash.clear
    notify
  end

  def get_type_notify(type)
    case type
    when "notice"
      return "success"
    when "error"
      return "error"
    end
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>

  <div class="form-group">
    <%= form.label t("description") %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t("acronym") %>
    <%= form.text_field :acronym, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label t("attributes_model.url_image") %>
    <%= form.text_field :urlImage, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t("attributes_model.mining_type") %>
    <%= form.select :mining_type_id, @mining_type_options,
      {}, class: "custom-select" %>
  </div>

  <div class="form-group">
    <%= form.submit t('create.coin'), class: "btn btn-success" %>
    <%= link_to t('links.back'), coins_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1><%= t("editing.coin") %></h1>

<%= render 'form', coin: @coin %>

app/views/coins/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t("attributes_model.description") %></th>
      <th><%= t("attributes_model.acronym") %></th>
      <th><%= t("attributes_model.url_image") %></th>
      <th><%= t("attributes_model.mining_type") %></th>
      <th colspan="2"><%= t("actions") %></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.urlImage, width:25, height:25 %></td>
        <td><%= coin.mining_type.acronym %></td>
        <td>
          <%= link_to(edit_coin_path(coin)) do %>
          <i class="fa fa-pencil fa-lg"></i>
          <% end%>
        </td>
        <td>
          <%= link_to(coin, method: :delete, data: { confirm: t("messages.confirm") }) do %>
            <i class="fa fa-trash fa-lg"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("links.new"), new_coin_path, class: "btn btn-primary" %>

app/views/coins/new.html.erb
<h1><%= t("new.coin") %></h1>

<%= render 'form', coin: @coin %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t("attributes_model.description") %></strong>
  <%= @coin.description %>
</p>

<p>
  <strong><%= t("attributes_model.acronym") %></strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong><%= t("attributes_model.url_image") %></strong>
  <%= @coin.urlImage %>
</p>

<p>
  <strong><%= t("attributes_model.mining_type") %></strong>
  <%= @coin.mining_type.description %>
</p>

<%= link_to t('links.edit'), edit_coin_path(@coin) %> |
<%= link_to t('links.back'), coins_path %>

app/views/layouts/adm.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>CABEÇALHO - ADM</h1>
    <%= yield %>
    <%# a variável yield renderiza qualquer das views como por exemplo: index.html.erb, edit.html.erb %>
    <h1>RODAPÉ - ADM</h1>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "welcome/navbar" %>
      <%= yield %>
      <%# a variável yield renderiza qualquer das views como por exemplo: index.html.erb, edit.html.erb %>
    </div>
  </body>
</html>

<%= javascript_tag(display_flash_messages) %>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <div class="form-group">
    <%= form.label t("description") %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t("acronym") %>
    <%= form.text_field :acronym, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit t('create.mining_type'), class: "btn btn-success"%>
    <%= link_to t('links.back'), mining_types_path, class: "btn btn-secondary" %>
  </div>
  <% end %>

app/views/mining_types/edit.html.erb
<h1><%= t("editing.mining_type") %></h1>

<%= render 'form', mining_type: @mining_type %>

app/views/mining_types/index.html.erb
<h1><%= MiningType.model_name.human(count: @mining_types.count) %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t("attributes_model.description") %></th>
      <th><%= t("attributes_model.acronym") %></th>
      <th colspan="2"><%= t("actions") %></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td>
          <%= link_to(edit_mining_type_path(mining_type)) do %>
          <i class="fa fa-pencil fa-lg"></i>
          <% end%>
        </td>
        <td>
          <%= link_to(mining_type, method: :delete, data: { confirm: t("messages.confirm") }) do %>
            <i class="fa fa-trash fa-lg"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("link.new"), new_mining_type_path, class: "btn btn-primary" %>

app/views/mining_types/new.html.erb
<h1><%= t("new.mining_type") %></h1>
<%= render 'form', mining_type: @mining_type %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @mining_type.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @mining_type.acronym %>
</p>

<%= link_to t('links.edit'), edit_mining_type_path(@mining_type) %> |
<%= link_to t('links.back'), mining_types_path %>

app/views/welcome/_menu.html.erb
<%= link_to t("coin"), coins_path, class: "btn-primary btn-lg", role: "button" %>
<%= link_to t("mining_type"), mining_types_path, class: "btn-primary btn-lg", role: "button" %>

app/views/welcome/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
    <ul class="navbar-nav mr-auto">
      <%= link_to "Home", root_path, class: "nav-link" %>
    </ul>
  </div>
  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "Português", translate("pt-BR"), class: "nav-link" %>
      </li>
        <li class="nav-item">
          <%= link_to "English", translate("en"), class: "nav-link" %>
        </li>
    </ul>
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= t("welcome") %></h1>
  <p class="lead"><%= t("messages.welcome") %></p>
  <hr class="my-4">
  <p><%= t("messages.menu") %></p>
  <%= render "menu" %>
</div>

<!--
<p><%= cookies[:curso] %></p>
<p>Idioma utilizado: <%= t("actual_locale") %></p>
<p><strong>Data:</strong> <%= l(Date.today) %>
<%= t("hello") %>
chamando partials

<p>
  Você está em ambiente de: <strong>  <%= ambiente_rails %> </strong>
</p>

<p>
  Eu sou uma variável de instância/sessão <%= @meu_nome %>
</p>

<p>
  Estou no curso de <%= @meu_curso%>
</p>